### ISSUE TITLE
Use old cache when internet not available

### ISSUE THREAD

**Issue by mtissington** [tinohager/Nager.PublicSuffix#19]
If the cache can't be refreshed then it would be good to be able to use the file currently in cache.

**Comment by tinohager** [comment]
i have fixed the documentation

**Comment by mtissington** [comment]
I'm confused here - I don't see how the code uses old cache even if it's present but not valid.
It's seems to me that is it's not valid then an attempt is made to get the data again, which may fail and then return null

**Comment by tinohager** [comment]
sorry please check the example again i fix it

**Comment by mtissington** [comment]
Thanks, however while the syntax of the code is now good. It still throws an exception on this line
`var domainParser = new DomainParser(webTldRuleProvider);` if the internet is not available.

Looking at the code, the above line ALWAYS attempts to validate the cache and load it if invalid.

So the additional code `IsCacheValid` will always return true.

**Comment by tinohager** [comment]
can you check again i have update the example again and push a new nuget package

**Comment by mtissington** [comment]
I have downloaded the latest nuget package and got the update, the exception is no longer thrown which is good. However it is still not possible to load the existing data or old data from the cache when the internet is not available. 

When the internet is not available - DomainParse has only 1 rule in it.

**Comment by tinohager** [comment]
If your internet not available increase the cache time or write a own implementation

**Comment by tinohager** [comment]
The ``ICacheProvider`` allow you to implement your own cache provider.

**Comment by mtissington** [comment]
OK, that won't work, I see more is required ...
